### ISSUE TITLE
delocate.delocating.DelocationError: wheel/PIL/.dylibs/libwebp.7.dylib already exists

### ISSUE THREAD

**Issue by hugovk** [python-pillow/pillow-wheels#133]
This has started happening for Python 3.8 on macOS since Travis changed from a 10.13.3 image to a 10.13.6 image:

```
Building wheels for collected packages: delocate
  Building wheel for delocate (setup.py): started
  Building wheel for delocate (setup.py): finished with status 'done'
  Created wheel for delocate: filename=delocate-0.8.0-cp38-none-any.whl size=101856 sha256=a8ed72c8c953b730b87150979092ef15f37998dbc7f66a384f2e874e3de21fb8
  Stored in directory: /Users/travis/Library/Caches/pip/wheels/a7/ec/01/fff106a59b5697042f1ff32814f1f112e3eee5a2c5239d7735
Successfully built delocate
Installing collected packages: delocate
Successfully installed delocate-0.8.0
Traceback (most recent call last):
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/lib/python3.8/site-packages/delocate/cmd/delocate_wheel.py", line 68, in main
    copied = delocate_wheel(wheel, out_wheel, lib_filt_func=lib_filt_func,
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/lib/python3.8/site-packages/delocate/delocating.py", line 376, in delocate_wheel
    copied_libs = delocate_path(package_path, lib_path,
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/lib/python3.8/site-packages/delocate/delocating.py", line 289, in delocate_path
    return copy_recurse(lib_path, copy_filt_func, copied)
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/lib/python3.8/site-packages/delocate/delocating.py", line 145, in copy_recurse
    _copy_required(lib_path, copy_filt_func, copied_libs)
  File "/Users/travis/build/python-pillow/pillow-wheels/venv/lib/python3.8/site-packages/delocate/delocating.py", line 230, in _copy_required
    raise DelocationError(out_path + ' already exists')
delocate.delocating.DelocationError: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpyrhzp83g/wheel/PIL/.dylibs/libwebp.7.dylib already exists
```

Failing build:
* https://travis-ci.org/python-pillow/pillow-wheels/jobs/627386267

Earlier passing build:
* https://travis-ci.org/python-pillow/pillow-wheels/jobs/624597203

**Comment by hugovk** [comment]
Reported at https://github.com/matthew-brett/delocate/issues/65.

**Comment by radarhere** [comment]
I've created PR #134 to resolve this.
