### ISSUE TITLE
Pillow wheel 5.1 broken on OS X 10.11.6 due to liblzma.5.dylib

### ISSUE THREAD

**Issue by WoLpH** [python-pillow/pillow-wheels#83]
It appears that the `liblzma.5.dylib` file was built for OS X 10.12 and up which means the build is broken for OS X 10.11.6

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /usr/local/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
```

**Comment by hugovk** [comment]
This is a duplicate of https://github.com/python-pillow/Pillow/issues/3068.

**Comment by WoLpH** [comment]
indeed a duplicate, I'll close its
